services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "4444:4200"
    volumes:
      - ./Frontend/src:/app/src
    depends_on:
      - backend

  backend:
    build:
      context: ./WebAPI
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=invoicikaDb;Username=postgres;Password=invoicika!123
    depends_on:
      - db
    volumes:
      - ./WebAPI:/app/webapi
    networks:
      - invoicika_backend

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=invoicika!123
      - POSTGRES_DB=invoicikaDb
    ports:
      - "5433:5432"
    volumes:
      - sql_data:/var/lib/postgresql/data
    networks:
      - invoicika_backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

networks:
  invoicika_backend:

volumes:
  sql_data:
